baseURL = "https://example.com"

# The name of this wonderful theme ;-).
theme = 'stateless'

# Basic metadata configuration for your blog.
title = "stateless"
author = "Jane Doe"
copyright = "Copyright © 2020, Jane Doe."
languageCode = "en-US"

[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "../assets"
    target = "assets"
  [[module.mounts]]
    source = "../layouts"
    target = "layouts"